encoding: utf-8
markdown: redcarpet
baseurl:
url: training.webmakerprototypes.org
languages: ['en','es']
default_language: 'en'
permalink: :categories/:title/
ga_tracking_code: UA-48377627-2
gems:
  - jekyll-redirect-from
